targets:
  $default:
    builders:
      toon_dart_generator|toon_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart

builders:
  toon_generator:
    import: "package:toon_dart_generator/src/builder.dart"
    builder_factories: ["toonGenerator"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source

